// SPDX-License-Identifier: AGPL-3.0-only
//! Symbolic-vs-Rust EOM check for the **T3 14-DOF chassis** (Decision #32): the hand-written
//! [`ChassisT3`] RHS must agree with the `SymPy` `KanesMethod` derivation to 1e-12 at every fixture
//! sample. The fixture is regenerated by `docs/derivations/t3_chassis_kane.ipynb` (CI re-executes it
//! and `git diff`s the result), so a sign error in either the Rust EOM or the symbolic source fails
//! this test. Sibling of `kane_fixture.rs` (the T2 check).

use serde_json::Value;

use outlap_core::bus::{Bus, ChannelInterner, CoreSignal, WheelSignal, WHEELS};
use outlap_core::state::{fast_slot_count, ChassisState, DerivView, StateView};
use outlap_vehicle::{ChassisParams, ChassisT3, RoadChannels, SuspensionParams, T3RoadVertical};

fn f(v: &Value, key: &str) -> f64 {
    v[key]
        .as_f64()
        .unwrap_or_else(|| panic!("missing/non-f64 fixture key {key}"))
}

/// Read a per-wheel array stored as `{prefix}{i}` for i in 0..4 (e.g. `w0..w3`, `d0_0..d0_3`).
fn arr4(v: &Value, prefix: &str) -> [f64; WHEELS] {
    let mut a = [0.0; WHEELS];
    for (i, out) in a.iter_mut().enumerate() {
        *out = f(v, &format!("{prefix}{i}"));
    }
    a
}

#[test]
#[allow(clippy::too_many_lines)] // one flat sample loop that maps 24 states + 127 named inputs
fn chassis_t3_rhs_matches_kane_derivation_to_1e_12() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/derivations/fixtures/t3_chassis_rhs.json"
    );
    let text =
        std::fs::read_to_string(path).expect("fixture present (run the T3 derivation notebook)");
    let doc: Value = serde_json::from_str(&text).expect("valid JSON");
    let front = [true, true, false, false];
    let samples = doc["samples"].as_array().expect("samples");
    assert!(!samples.is_empty());

    // state slots in the RHS/state_order, for indexing the expected vector.
    let state_slots = [
        ChassisState::S,
        ChassisState::N,
        ChassisState::PsiRel,
        ChassisState::Vx,
        ChassisState::Vy,
        ChassisState::YawRate,
        ChassisState::OmegaFl,
        ChassisState::OmegaFr,
        ChassisState::OmegaRl,
        ChassisState::OmegaRr,
        ChassisState::Heave,
        ChassisState::Pitch,
        ChassisState::Roll,
        ChassisState::HeaveRate,
        ChassisState::PitchRate,
        ChassisState::RollRate,
        ChassisState::ZuFl,
        ChassisState::ZuFr,
        ChassisState::ZuRl,
        ChassisState::ZuRr,
        ChassisState::ZuRateFl,
        ChassisState::ZuRateFr,
        ChassisState::ZuRateRl,
        ChassisState::ZuRateRr,
    ];

    // Optional: dump the per-sample per-state residuals to CSV for the verification figure.
    let mut csv = String::new();
    let dump = std::env::var("OUTLAP_T3_RESIDUAL_CSV").ok();
    if dump.is_some() {
        csv.push_str("sample,state,rust,sympy,abs,rel\n");
    }

    let mut worst = 0.0f64;
    for (si, sample) in samples.iter().enumerate() {
        let inp = &sample["inputs"];

        let params = ChassisParams::<f64>::from_f64(
            f(inp, "m"),
            f(inp, "izz"),
            arr4(inp, "x"),
            arr4(inp, "y"),
            front,
            arr4(inp, "R"),
            arr4(inp, "iw"),
        );
        assert!((params.gravity - f(inp, "g")).abs() < 1e-12);

        let susp = SuspensionParams::<f64> {
            sprung_mass: f(inp, "ms"),
            ixx: f(inp, "ixx"),
            iyy: f(inp, "iyy"),
            h_s: f(inp, "hs"),
            h_cg: f(inp, "hcg"),
            h_ra: f(inp, "hra"),
            wheelbase: f(inp, "wheelbase"),
            track_f: f(inp, "tf"),
            track_r: f(inp, "tr"),
            anti_dive: f(inp, "anti_d"),
            anti_squat: f(inp, "anti_s"),
            arb_f: f(inp, "karb_f"),
            arb_r: f(inp, "karb_r"),
            bumpstop_smooth: f(inp, "sbs"),
            k_ride: arr4(inp, "kr"),
            static_defl: arr4(inp, "d0_"),
            damp_bump: arr4(inp, "cb"),
            damp_rebound: arr4(inp, "cr"),
            bumpstop_rate: arr4(inp, "kbs"),
            bumpstop_gap: arr4(inp, "gbs"),
            k_tyre: arr4(inp, "ktz"),
            c_tyre: arr4(inp, "ctz"),
            tyre_static_defl: arr4(inp, "dtz0_"),
            unsprung_mass: arr4(inp, "mu"),
        };

        let mut interner = ChannelInterner::new();
        let road = RoadChannels::intern(&mut interner);
        let road_v = T3RoadVertical::intern(&mut interner);
        let chassis = ChassisT3::new(params, susp, road, road_v);

        let mut bus = Bus::<f64>::with_interner(&interner, 1);
        bus.set(CoreSignal::Steer, 0, f(inp, "steer"));
        bus.set(CoreSignal::AeroDrag, 0, f(inp, "drag"));
        bus.set(CoreSignal::YawMomentDemand, 0, f(inp, "dmz"));
        bus.set_channel(road.kappa, 0, f(inp, "kappa"));
        bus.set_channel(road.grade, 0, f(inp, "grade"));
        bus.set_channel(road.banking, 0, f(inp, "bank"));
        bus.set_channel(road.kappa_v, 0, f(inp, "kappa_v"));
        let fxw = arr4(inp, "fxw");
        let fyw = arr4(inp, "fyw");
        let mzw = arr4(inp, "mzw");
        let tau = arr4(inp, "tau");
        let zr = arr4(inp, "zr");
        let zrd = arr4(inp, "zrd");
        for w in 0..WHEELS {
            bus.set_wheel(WheelSignal::TireFx, w, 0, fxw[w]);
            bus.set_wheel(WheelSignal::TireFy, w, 0, fyw[w]);
            bus.set_wheel(WheelSignal::TireMz, w, 0, mzw[w]);
            bus.set_wheel(WheelSignal::WheelDriveTorque, w, 0, tau[w]);
            bus.set_wheel(WheelSignal::WheelBrakeTorque, w, 0, 0.0);
            bus.set_channel(road_v.height[w], 0, zr[w]);
            bus.set_channel(road_v.rate[w], 0, zrd[w]);
        }

        let n_slots = fast_slot_count();
        let mut fast = vec![0.0f64; n_slots];
        let set = |fast: &mut [f64], s: ChassisState, v: f64| fast[s as usize] = v;
        set(&mut fast, ChassisState::N, f(inp, "n"));
        set(&mut fast, ChassisState::PsiRel, f(inp, "psi"));
        set(&mut fast, ChassisState::Vx, f(inp, "vx"));
        set(&mut fast, ChassisState::Vy, f(inp, "vy"));
        set(&mut fast, ChassisState::YawRate, f(inp, "r"));
        let w = arr4(inp, "w");
        set(&mut fast, ChassisState::OmegaFl, w[0]);
        set(&mut fast, ChassisState::OmegaFr, w[1]);
        set(&mut fast, ChassisState::OmegaRl, w[2]);
        set(&mut fast, ChassisState::OmegaRr, w[3]);
        set(&mut fast, ChassisState::Heave, f(inp, "z"));
        set(&mut fast, ChassisState::Pitch, f(inp, "th"));
        set(&mut fast, ChassisState::Roll, f(inp, "ph"));
        set(&mut fast, ChassisState::HeaveRate, f(inp, "zd"));
        set(&mut fast, ChassisState::PitchRate, f(inp, "thd"));
        set(&mut fast, ChassisState::RollRate, f(inp, "phd"));
        let zu = arr4(inp, "zu");
        let zud = arr4(inp, "zud");
        set(&mut fast, ChassisState::ZuFl, zu[0]);
        set(&mut fast, ChassisState::ZuFr, zu[1]);
        set(&mut fast, ChassisState::ZuRl, zu[2]);
        set(&mut fast, ChassisState::ZuRr, zu[3]);
        set(&mut fast, ChassisState::ZuRateFl, zud[0]);
        set(&mut fast, ChassisState::ZuRateFr, zud[1]);
        set(&mut fast, ChassisState::ZuRateRl, zud[2]);
        set(&mut fast, ChassisState::ZuRateRr, zud[3]);

        let mut dfast = vec![0.0f64; n_slots];
        {
            let sv = StateView::new(&fast, 1, 0);
            let mut dv = DerivView::new(&mut dfast, 1, 0);
            outlap_core::block::Block::derivatives(&chassis, &sv, &mut bus, &mut dv, 0);
        }

        let expected = sample["rhs"].as_array().unwrap();
        for (i, slot) in state_slots.iter().enumerate() {
            let rust = dfast[*slot as usize];
            let e = expected[i].as_f64().unwrap();
            let diff = (rust - e).abs();
            // Mixed absolute+relative gate: 1e-12 absolute for O(1) entries, 1e-12 RELATIVE for the
            // stiff unsprung accelerations (O(10³ m/s²): k_tz≈250 kN/m over ~15 kg unsprung), whose
            // f64 summation order differs from SymPy's by a few ULP. A sign/formula error moves an
            // entry by O(1) relative — orders of magnitude above this gate.
            let rel = diff / (1.0 + e.abs());
            worst = worst.max(rel);
            if dump.is_some() {
                use std::fmt::Write as _;
                let _ = writeln!(csv, "{si},{i},{rust:e},{e:e},{diff:e},{rel:e}");
            }
            assert!(
                rel < 1e-12,
                "state {i} ({slot:?}): rust={rust} sympy={e} abs={diff:e} rel={rel:e}"
            );
        }
    }
    assert!(worst < 1e-12, "worst-case relative disagreement {worst:e}");
    println!("T3 Kane fixture: worst-case relative |rust − sympy| = {worst:e}");
    if let Some(path) = dump {
        std::fs::write(&path, csv).expect("write residual CSV");
    }
}
