// SPDX-License-Identifier: AGPL-3.0-only
//! Symbolic-vs-Rust EOM check (Decision #32): the hand-written [`Chassis`] RHS must agree with the
//! `SymPy` `KanesMethod` derivation to 1e-12 at every fixture sample. The fixture is regenerated by
//! `docs/derivations/t2_chassis_kane.ipynb` (CI re-executes it and `git diff`s the result), so a
//! sign error in either the Rust EOM or the symbolic source fails this test.

use serde_json::Value;

use outlap_core::bus::{Bus, ChannelInterner, CoreSignal, WheelSignal, WHEELS};
use outlap_core::state::{ChassisState, DerivView, StateView};
use outlap_vehicle::{Chassis, ChassisParams, RoadChannels};

fn arr4(v: &Value, key: &str) -> [f64; 4] {
    let a = v[key].as_array().expect("array");
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
        a[3].as_f64().unwrap(),
    ]
}

fn f(v: &Value, key: &str) -> f64 {
    v[key].as_f64().expect("f64")
}

#[test]
fn chassis_rhs_matches_kane_derivation_to_1e_12() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/derivations/fixtures/t2_chassis_rhs.json"
    );
    let text =
        std::fs::read_to_string(path).expect("fixture present (run the derivation notebook)");
    let doc: Value = serde_json::from_str(&text).expect("valid JSON");
    let front = [true, true, false, false];
    let samples = doc["samples"].as_array().expect("samples");
    assert!(!samples.is_empty());

    let mut worst = 0.0f64;
    for sample in samples {
        let inp = &sample["inputs"];
        let params = ChassisParams::<f64>::from_f64(
            f(inp, "m"),
            f(inp, "izz"),
            arr4(inp, "x"),
            arr4(inp, "y"),
            front,
            arr4(inp, "R"),
            arr4(inp, "Iw"),
        );
        // `from_f64` sets gravity to standard g; the fixture uses the same constant.
        assert!((params.gravity - f(inp, "g")).abs() < 1e-12);

        let mut interner = ChannelInterner::new();
        let road = RoadChannels::intern(&mut interner);
        let chassis = Chassis::new(params, road);

        let mut bus = Bus::<f64>::with_interner(&interner, 1);
        bus.set(CoreSignal::Steer, 0, f(inp, "steer"));
        bus.set(CoreSignal::AeroDrag, 0, f(inp, "drag"));
        bus.set(CoreSignal::YawMomentDemand, 0, f(inp, "dmz"));
        bus.set_channel(road.kappa, 0, f(inp, "kappa"));
        bus.set_channel(road.grade, 0, f(inp, "grade"));
        bus.set_channel(road.banking, 0, f(inp, "bank"));
        let fxw = arr4(inp, "fxw");
        let fyw = arr4(inp, "fyw");
        let mzw = arr4(inp, "mzw");
        let tau = arr4(inp, "tau");
        for w in 0..WHEELS {
            bus.set_wheel(WheelSignal::TireFx, w, 0, fxw[w]);
            bus.set_wheel(WheelSignal::TireFy, w, 0, fyw[w]);
            bus.set_wheel(WheelSignal::TireMz, w, 0, mzw[w]);
            bus.set_wheel(WheelSignal::WheelDriveTorque, w, 0, tau[w]);
            bus.set_wheel(WheelSignal::WheelBrakeTorque, w, 0, 0.0);
        }

        let n_slots = outlap_core::state::fast_slot_count();
        let mut fast = vec![0.0f64; n_slots];
        fast[ChassisState::N as usize] = f(inp, "n");
        fast[ChassisState::PsiRel as usize] = f(inp, "psi");
        fast[ChassisState::Vx as usize] = f(inp, "vx");
        fast[ChassisState::Vy as usize] = f(inp, "vy");
        fast[ChassisState::YawRate as usize] = f(inp, "r");
        let omega = arr4(inp, "omega");
        fast[ChassisState::OmegaFl as usize] = omega[0];
        fast[ChassisState::OmegaFr as usize] = omega[1];
        fast[ChassisState::OmegaRl as usize] = omega[2];
        fast[ChassisState::OmegaRr as usize] = omega[3];

        let mut dfast = vec![0.0f64; n_slots];
        {
            let sv = StateView::new(&fast, 1, 0);
            let mut dv = DerivView::new(&mut dfast, 1, 0);
            outlap_core::block::Block::derivatives(&chassis, &sv, &mut bus, &mut dv, 0);
        }

        let rust = [
            dfast[ChassisState::S as usize],
            dfast[ChassisState::N as usize],
            dfast[ChassisState::PsiRel as usize],
            dfast[ChassisState::Vx as usize],
            dfast[ChassisState::Vy as usize],
            dfast[ChassisState::YawRate as usize],
            dfast[ChassisState::OmegaFl as usize],
            dfast[ChassisState::OmegaFr as usize],
            dfast[ChassisState::OmegaRl as usize],
            dfast[ChassisState::OmegaRr as usize],
        ];
        let expected = sample["rhs"].as_array().unwrap();
        for (i, r) in rust.iter().enumerate() {
            let e = expected[i].as_f64().unwrap();
            let diff = (r - e).abs();
            worst = worst.max(diff);
            assert!(diff < 1e-12, "state {i}: rust={r} sympy={e} diff={diff:e}");
        }
    }
    // A visible margin below the gate (documented in the theory page).
    assert!(worst < 1e-12, "worst-case disagreement {worst:e}");
}
