# SPDX-License-Identifier: AGPL-3.0-only
"""Render the QSS-powertrain theory figure (docs/theory/img/qss_powertrain.png).

Reads the committed synthetic `.ptm` sidecars (crates/outlap-schema/tests/fixtures/d.ptm.maps.parquet
and tables/ice_v6.parquet — generated by that directory's gen_ptm_maps.py) and reproduces the PR4
story in four panels:

  (a) the drive-unit efficiency map η(speed, torque),
  (b) the differential torque split vs left/right grip ratio (open / locked / LSD),
  (c) energy closure — source power vs mechanical + loss at the drive-quadrant nodes,
  (d) the ICE brake-thermal-efficiency map and the fuel-mass rate it implies under load.

The differential split mirrors `DiffModel::split` (outlap-qss). Synthetic only — never PDT data.

Run from anywhere:  python python/tools/plot_qss_powertrain.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pyarrow.parquet as pq

plt.style.use("seaborn-v0_8-darkgrid")

_ROOT = Path(__file__).resolve().parents[2]
_FIXTURES = _ROOT / "crates" / "outlap-schema" / "tests" / "fixtures"
_DU = _FIXTURES / "d.ptm.maps.parquet"
_ICE = _FIXTURES / "tables" / "ice_v6.parquet"
_OUT = _ROOT / "docs" / "theory" / "img" / "qss_powertrain.png"

RPM_TO_RAD = np.pi / 30.0
FUEL_LHV = 43.0e6  # J/kg


def _grid(path: Path):
    """Load a long/tidy `.ptm` sidecar into (speed_axis, torque_axis, eff[ns,nt], loss[ns,nt])."""
    t = pq.read_table(path)
    speed = np.asarray(t.column("speed_rpm"))
    torque = np.asarray(t.column("torque_nm"))
    eff = np.asarray(t.column("efficiency"))
    loss = np.asarray(t.column("loss_w"))
    saxis = np.unique(speed)
    taxis = np.unique(torque)
    ns, nt = saxis.size, taxis.size
    return saxis, taxis, eff.reshape(ns, nt), loss.reshape(ns, nt)


def _diff_split(kind: str, t: float, cl: float, cr: float, preload=0.0, ramp=0.0):
    """Mirror of outlap-qss `DiffModel::split` — returns (left, right) output-shaft torques."""
    if kind == "open":
        return 0.5 * t, 0.5 * t
    total = cl + cr
    left, right = t * cl / total, t * cr / total
    if kind in ("locked", "solid"):
        return left, right
    bias = preload + ramp * abs(t)  # lsd
    half = 0.5 * (t - np.clip(left - right, -bias, bias))
    return t - half, half


def _panel_eff_map(ax, saxis, taxis, eff, title):
    mesh = ax.pcolormesh(saxis, taxis, eff.T, cmap="viridis", shading="gouraud", vmin=0.0)
    ax.set_xlabel("shaft speed [rpm]")
    ax.set_ylabel("torque [N·m]")
    ax.set_title(title)
    return mesh


def _panel_diff(ax):
    frac = np.linspace(0.1, 0.9, 41)  # left-side grip fraction cap_left / (cap_left + cap_right)
    tau = 200.0
    for kind, style in [("open", "-"), ("locked", "--"), ("lsd", "-.")]:
        share = [
            _diff_split(kind, tau, f, 1.0 - f, preload=0.1, ramp=0.30)[0] / tau for f in frac
        ]
        ax.plot(frac, share, style, lw=2.2, label=kind.upper())
    ax.plot([0.1, 0.9], [0.1, 0.9], color="0.6", lw=0.8, ls=":", label="grip line")
    ax.set_xlabel("left-wheel grip fraction")
    ax.set_ylabel("left-wheel torque share")
    ax.set_title("(b) differential torque split")
    ax.legend(fontsize=8, loc="upper left")


def _panel_energy(ax, saxis, taxis, eff, loss):
    # Drive quadrant nodes: source = mech / η should equal mech + loss.
    src, ml = [], []
    for i, rpm in enumerate(saxis):
        for j, tau in enumerate(taxis):
            if tau <= 0.0 or eff[i, j] <= 0.0:
                continue
            mech = tau * rpm * RPM_TO_RAD
            src.append(mech / eff[i, j] / 1e3)  # kW
            ml.append((mech + loss[i, j]) / 1e3)
    src, ml = np.array(src), np.array(ml)
    ax.scatter(src, ml, s=18, color="#2a7", alpha=0.8, edgecolor="k", linewidth=0.3)
    lim = [0.0, max(src.max(), ml.max()) * 1.05]
    ax.plot(lim, lim, color="0.4", lw=1.0, ls="--")
    ax.set_xlim(lim)
    ax.set_ylim(lim)
    ax.set_xlabel("source power  P_src = P_mech/η  [kW]")
    ax.set_ylabel("mechanical + loss  [kW]")
    ax.set_title("(c) energy closure  (source = mech + loss)")


def _panel_ice(ax, saxis, taxis, eff):
    mesh = ax.pcolormesh(saxis, taxis, eff.T, cmap="magma", shading="gouraud", vmin=0.0)
    # Fuel-mass-rate contours: ṁ = P_mech / η / LHV (g/s), drive quadrant only.
    ss, tt = np.meshgrid(saxis, taxis, indexing="ij")
    mech = tt * ss * RPM_TO_RAD
    with np.errstate(divide="ignore", invalid="ignore"):
        fuel_gs = np.where(eff > 0.0, mech / eff / FUEL_LHV * 1e3, np.nan)
    cs = ax.contour(ss, tt, fuel_gs, levels=[2, 5, 10, 15, 20], colors="w", linewidths=0.8)
    ax.clabel(cs, inline=True, fontsize=7, fmt="%.0f g/s")
    ax.set_xlabel("engine speed [rpm]")
    ax.set_ylabel("torque [N·m]")
    ax.set_title("(d) ICE thermal efficiency + fuel rate")
    return mesh


def main() -> None:
    du_s, du_t, du_eff, du_loss = _grid(_DU)
    ice_s, ice_t, ice_eff, _ = _grid(_ICE)

    fig, axes = plt.subplots(2, 2, figsize=(11, 8))
    m_du = _panel_eff_map(axes[0, 0], du_s, du_t, du_eff, "(a) drive-unit efficiency  η(n, τ)")
    fig.colorbar(m_du, ax=axes[0, 0], label="η")
    _panel_diff(axes[0, 1])
    _panel_energy(axes[1, 0], du_s, du_t, du_eff, du_loss)
    m_ice = _panel_ice(axes[1, 1], ice_s, ice_t, ice_eff)
    fig.colorbar(m_ice, ax=axes[1, 1], label="η_thermal")

    fig.suptitle(
        "QSS topology powertrain — synthetic maps (PR4)", fontsize=13, fontweight="bold"
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(_OUT, dpi=110)
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    main()
