# SPDX-License-Identifier: AGPL-3.0-only
"""Render the g-g-g-v envelope theory figure (docs/theory/img/ggv_envelope.png).

Drives the figure from the **real** ``GgvEnvelope`` generator: it runs the committed Rust example
``crates/outlap-qss/examples/ggv_traces.rs`` (which generates the actual T1-trim envelope and its
Decision #31 corrections on a committed fixture) and plots its CSV output. Nothing here re-implements
the model.

Four panels:
  (a) g-g sections a_y(a_x) at three speeds (flat ground) — the classical friction diagram.
  (b) the apparent-gravity axis: pure-lateral grip vs g_normal (banking / crest / compression).
  (c) speed dependence: pure-lateral grip rises with v as downforce loads the tyres.
  (d) the Decision #31 correction to +15% tyre grip vs a full envelope re-solve (the truth).

Run from anywhere:  python python/tools/plot_ggv_envelope.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

plt.style.use("seaborn-v0_8-darkgrid")

_ROOT = Path(__file__).resolve().parents[2]
_OUT = _ROOT / "docs" / "theory" / "img" / "ggv_envelope.png"


def _run_traces() -> dict[str, list[tuple[float, float, float]]]:
    """Run the Rust example (release) and group its CSV rows by section."""
    proc = subprocess.run(
        ["cargo", "run", "--release", "-q", "-p", "outlap-qss", "--example", "ggv_traces"],
        cwd=_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    rows: dict[str, list[tuple[float, float, float]]] = {}
    for line in proc.stdout.splitlines():
        if not line or line.startswith("#") or line.startswith("section"):
            continue
        sec, x, a, b = (line.split(",") + ["0"])[:4]
        rows.setdefault(sec, []).append((float(x), float(a), float(b)))
    return rows


def main() -> None:
    rows = _run_traces()
    fig, axes = plt.subplots(2, 2, figsize=(11, 8.4))

    # (a) g-g sections at three speeds.
    ax = axes[0, 0]
    speeds = sorted({r[2] for r in rows["gg"]})
    for v in speeds:
        pts = [(r[0], r[1]) for r in rows["gg"] if r[2] == v]
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        ax.plot(xs, ys, "-", lw=2.0, label=f"{v:.0f} m/s")
    ax.set(
        xlabel="longitudinal $a_x$ [m/s²]",
        ylabel="lateral $a_y$ [m/s²]",
        title="(a) g-g sections (flat, $g_n = g$)",
    )
    ax.legend(title="speed", loc="lower center", ncols=3)

    # (b) apparent-gravity axis.
    ax = axes[0, 1]
    speeds = sorted({r[2] for r in rows["gnv"]})
    for v in speeds:
        pts = [(r[0], r[1]) for r in rows["gnv"] if r[2] == v]
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        ax.plot(xs, ys, "-", lw=2.0, label=f"{v:.0f} m/s")
    ax.axvline(1.0, color="0.5", ls="--", lw=1.0)
    ax.set(
        xlabel="apparent gravity $g_{normal}/g$",
        ylabel="pure-lateral grip $a_y$ [m/s²]",
        title="(b) g-g-g-v: banking / crest / compression",
    )
    ax.legend(title="speed", loc="upper left")

    # (c) speed dependence of pure-lateral grip.
    ax = axes[1, 0]
    vs = np.array([r[0] for r in rows["speed"]])
    ay = np.array([r[1] for r in rows["speed"]])
    ax.plot(vs, ay, "-", lw=2.4, color="tab:blue")
    ax.set(
        xlabel="speed $v$ [m/s]",
        ylabel="pure-lateral grip $a_y$ [m/s²]",
        title="(c) downforce raises grip with speed",
    )

    # (d) Decision #31 correction vs full re-solve.
    ax = axes[1, 1]
    vs = np.array([r[0] for r in rows["corr"]])
    corrected = np.array([r[1] for r in rows["corr"]])
    truth = np.array([r[2] for r in rows["corr"]])
    ax.plot(vs, truth, "-", lw=2.6, color="tab:green", label="full T1 re-solve (μ +15%)")
    ax.plot(vs[::4], corrected[::4], "o", ms=5, color="tab:red", label="corrected envelope")
    ax.set(
        xlabel="speed $v$ [m/s]",
        ylabel="pure-lateral grip $a_y$ [m/s²]",
        title="(d) Decision #31 correction vs re-solve",
    )
    ax.legend(loc="upper left")

    fig.suptitle(
        "g-g-g-v envelope — generated by the T1 trim (outlap-qss GgvEnvelope)",
        fontsize=13,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(_OUT, dpi=130)
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    main()
