# SPDX-License-Identifier: AGPL-3.0-only
"""Type stubs for the `outlap_core` extension module (shipped in the wheel by maturin)."""

import numpy as np
from numpy.typing import NDArray

DEFAULT_DS_M: float

class Tyre:
    notes: list[tuple[str, str]]
    citation: str
    fnomin: float
    unloaded_radius: float
    p_cold: float
    @staticmethod
    def load(path: str) -> Tyre: ...
    def forces(
        self,
        kappa: NDArray[np.float64],
        alpha: NDArray[np.float64],
        gamma: NDArray[np.float64],
        fz: NDArray[np.float64],
        p: NDArray[np.float64],
        vx: NDArray[np.float64],
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
    ]: ...
    def peak_mu(self, fz: float, p: float) -> tuple[float, float]: ...

class Track:
    @staticmethod
    def load(dir: str) -> Track: ...
    def name(self) -> str: ...
    def length(self) -> float: ...
    def is_closed(self) -> bool: ...
    def sample(self, ds_m: float) -> dict[str, NDArray[np.float64]]: ...

class Raceline:
    ds_m: float
    generator: str
    iterations: int
    def s(self) -> NDArray[np.float64]: ...
    def n(self) -> NDArray[np.float64]: ...
    def line(self) -> Track: ...

class Envelope:
    notes: list[str]
    def ay_boundary(self, v: float, ax: float, g_normal: float) -> float: ...
    def accel_limit(self, v: float, g_normal: float) -> float: ...
    def brake_limit(self, v: float, g_normal: float) -> float: ...
    def drag_accel(self, v: float) -> float: ...
    def domain(self) -> list[list[float]]: ...
    def shape(self) -> list[int]: ...
    def mass_ref(self) -> float: ...

class Lap:
    lap_time_s: float
    tier: str
    fz_coupling: str
    flat_track: bool
    wheels: list[str]
    notes: list[str]
    resolved_hash: str
    envelope: Envelope | None
    def s(self) -> NDArray[np.float64]: ...
    def v(self) -> NDArray[np.float64]: ...
    def ax(self) -> NDArray[np.float64]: ...
    def ay(self) -> NDArray[np.float64]: ...
    def t(self) -> NDArray[np.float64]: ...
    def x(self) -> NDArray[np.float64]: ...
    def y(self) -> NDArray[np.float64]: ...
    def z(self) -> NDArray[np.float64]: ...
    # Per-wheel channels (shape n x 4, wheel order FL/FR/RL/RR); None for tier t0.
    def vertical_load_n(self) -> NDArray[np.float64] | None: ...
    def slip_ratio(self) -> NDArray[np.float64] | None: ...
    def slip_angle_rad(self) -> NDArray[np.float64] | None: ...
    def force_long_n(self) -> NDArray[np.float64] | None: ...
    def force_lat_n(self) -> NDArray[np.float64] | None: ...
    # Setup metrics (per station); None for tier t0.
    def understeer_gradient(self) -> NDArray[np.float64] | None: ...
    def aero_front_share(self) -> NDArray[np.float64] | None: ...
    # Slow-state channels (per station); None unless a coupled electrified stack was active.
    # `machine_temp_c` is independently None when the pack marches without a thermal network.
    def state_of_charge(self) -> NDArray[np.float64] | None: ...
    def machine_temp_c(self) -> NDArray[np.float64] | None: ...
    # ERS energy-manager channels (per station, electrical W, realized); None unless the 2026
    # energy manager governed the march (M6 PR2).
    def deploy_power_w(self) -> NDArray[np.float64] | None: ...
    def harvest_power_w(self) -> NDArray[np.float64] | None: ...
    # Tyre-thermal slow-state channels (per station, representative front tyre); None unless
    # `tire_thermal=True` opted the QSS march in.
    def tire_surface_c(self) -> NDArray[np.float64] | None: ...
    def tire_carcass_c(self) -> NDArray[np.float64] | None: ...
    def tire_gas_c(self) -> NDArray[np.float64] | None: ...
    def tire_wear_mm(self) -> NDArray[np.float64] | None: ...
    def tire_damage(self) -> NDArray[np.float64] | None: ...
    def tire_grip(self) -> NDArray[np.float64] | None: ...

class TransientLap:
    """A solved transient (T2) lap: time-indexed channels on a fixed `dt` grid."""

    lap_time_s: float
    tier: str
    fz_coupling: str
    flat_track: bool
    dt_s: float
    integrator_order: int
    speed_margin: float
    completed: bool
    wheels: list[str]
    notes: list[str]
    resolved_hash: str
    def __len__(self) -> int: ...
    # Scalar channels over `time`.
    def t(self) -> NDArray[np.float64]: ...
    def s(self) -> NDArray[np.float64]: ...
    def n(self) -> NDArray[np.float64]: ...
    def psi_rel(self) -> NDArray[np.float64]: ...
    def vx(self) -> NDArray[np.float64]: ...
    def vy(self) -> NDArray[np.float64]: ...
    def yaw_rate(self) -> NDArray[np.float64]: ...
    def ax(self) -> NDArray[np.float64]: ...
    def ay(self) -> NDArray[np.float64]: ...
    def steer(self) -> NDArray[np.float64]: ...
    def throttle(self) -> NDArray[np.float64]: ...
    def brake(self) -> NDArray[np.float64]: ...
    def x(self) -> NDArray[np.float64]: ...
    def y(self) -> NDArray[np.float64]: ...
    def z(self) -> NDArray[np.float64]: ...
    # Rule-based control-layer telemetry.
    def gear(self) -> NDArray[np.float64]: ...
    def torque_scale(self) -> NDArray[np.float64]: ...
    def yaw_moment_nm(self) -> NDArray[np.float64]: ...
    def regen_power_w(self) -> NDArray[np.float64]: ...
    def traction_power_w(self) -> NDArray[np.float64]: ...
    def regen_torque_front_nm(self) -> NDArray[np.float64]: ...
    def regen_torque_rear_nm(self) -> NDArray[np.float64]: ...
    # Per-wheel channels (shape n x 4, wheel order FL/FR/RL/RR).
    def omega(self) -> NDArray[np.float64]: ...
    def vertical_load_n(self) -> NDArray[np.float64]: ...
    def slip_ratio(self) -> NDArray[np.float64]: ...
    def slip_angle_rad(self) -> NDArray[np.float64]: ...
    def force_long_n(self) -> NDArray[np.float64]: ...
    def force_lat_n(self) -> NDArray[np.float64]: ...
    # Slow states; None when the car carries no battery.
    def state_of_charge(self) -> NDArray[np.float64] | None: ...
    def pack_temp_c(self) -> NDArray[np.float64] | None: ...
    # Per-wheel tyre-thermal channels (shape n x 4); None unless the tyre-thermal stack was attached.
    def tire_surface_c(self) -> NDArray[np.float64] | None: ...
    def tire_carcass_c(self) -> NDArray[np.float64] | None: ...
    def tire_gas_c(self) -> NDArray[np.float64] | None: ...
    def tire_wear_mm(self) -> NDArray[np.float64] | None: ...
    def tire_damage(self) -> NDArray[np.float64] | None: ...
    def tire_grip(self) -> NDArray[np.float64] | None: ...

class QssStint:
    """A solved QSS stint: `n_laps` T0/T1 laps carrying the tyre-thermal state lap-to-lap."""

    n_laps: int
    tier: str
    fz_coupling: str
    flat_track: bool
    resolved_hash: str
    notes: list[str]
    def __len__(self) -> int: ...
    def s(self) -> NDArray[np.float64]: ...
    def lap_time_s(self) -> NDArray[np.float64]: ...
    # Per-(lap x station) channels (shape n_laps x n_stations).
    def v(self) -> NDArray[np.float64]: ...
    # Representative-tyre channels; None when the tyre march was off.
    def tire_surface_c(self) -> NDArray[np.float64] | None: ...
    def tire_carcass_c(self) -> NDArray[np.float64] | None: ...
    def tire_gas_c(self) -> NDArray[np.float64] | None: ...
    def tire_wear_mm(self) -> NDArray[np.float64] | None: ...
    def tire_damage(self) -> NDArray[np.float64] | None: ...
    def tire_grip(self) -> NDArray[np.float64] | None: ...
    # Per-(lap x station) pack SoC, carried continuously across lap boundaries; None without a
    # battery. `pack_temp_c`/`machine_temp_c` are per-lap end-of-lap (shape n_laps).
    def state_of_charge(self) -> NDArray[np.float64] | None: ...
    def pack_temp_c(self) -> NDArray[np.float64] | None: ...
    def machine_temp_c(self) -> NDArray[np.float64] | None: ...

class TransientStint:
    """A solved transient (T2) stint: per-lap summaries over a `lap` axis."""

    n_laps: int
    requested_laps: int
    tier: str
    fz_coupling: str
    flat_track: bool
    dt_s: float
    integrator_order: int
    speed_margin: float
    completed: bool
    wheels: list[str]
    resolved_hash: str
    notes: list[str]
    def __len__(self) -> int: ...
    def lap_time_s(self) -> NDArray[np.float64]: ...
    # Per-(lap x wheel) end-of-lap tyre state (shape n_laps x 4); None without the tyre stack.
    def tire_surface_c(self) -> NDArray[np.float64] | None: ...
    def tire_carcass_c(self) -> NDArray[np.float64] | None: ...
    def tire_gas_c(self) -> NDArray[np.float64] | None: ...
    def tire_wear_mm(self) -> NDArray[np.float64] | None: ...
    def tire_damage(self) -> NDArray[np.float64] | None: ...
    def tire_grip(self) -> NDArray[np.float64] | None: ...
    def tire_peak_surface_c(self) -> NDArray[np.float64] | None: ...
    # Per-lap end-of-lap pack state (shape n_laps); None without a battery.
    def state_of_charge(self) -> NDArray[np.float64] | None: ...
    def pack_temp_c(self) -> NDArray[np.float64] | None: ...

def min_curvature(
    track: Track,
    half_width_m: float,
    ds_m: float = 2.0,
    margin_m: float = 0.3,
    epsilon: float = 1e-8,
) -> Raceline: ...
def time_weighted(
    vehicle_dir: str,
    track: Track,
    half_width_m: float,
    ds_m: float = 2.0,
    iterations: int = 3,
    margin_m: float = 0.3,
    epsilon: float = 1e-8,
    tol: float = 1e-3,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    sim: dict[str, object] | None = None,
) -> Raceline: ...
def solve_lap(
    vehicle_dir: str,
    track: Track,
    ds_m: float = ...,
    raceline_ds_m: float | None = None,
    raceline_generator: str | None = None,
    raceline_iterations: int | None = None,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    tier: str | None = None,
    sim: dict[str, object] | None = None,
    tire_thermal: bool = False,
    initial_soc: float | None = None,
    override: bool = False,
    us_schedule: dict[str, object] | None = None,
) -> Lap: ...
def solve_transient_lap(
    vehicle_dir: str,
    track: Track,
    ds_m: float = ...,
    raceline_ds_m: float | None = None,
    raceline_generator: str | None = None,
    raceline_iterations: int | None = None,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    sim: dict[str, object] | None = None,
    speed_margin: float = ...,
    initial_soc: float | None = None,
    tire_thermal: bool = False,
    override: bool = False,
    us_schedule: dict[str, object] | None = None,
) -> TransientLap: ...
def solve_stint(
    vehicle_dir: str,
    track: Track,
    n_laps: int,
    ds_m: float = ...,
    raceline_ds_m: float | None = None,
    raceline_generator: str | None = None,
    raceline_iterations: int | None = None,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    tier: str | None = None,
    sim: dict[str, object] | None = None,
    tire_thermal: bool = True,
    initial_tire_temp_c: float | None = None,
    initial_soc: float | None = None,
    override: bool = False,
    us_schedule: dict[str, object] | None = None,
) -> QssStint: ...
def solve_transient_stint(
    vehicle_dir: str,
    track: Track,
    n_laps: int,
    ds_m: float = ...,
    raceline_ds_m: float | None = None,
    raceline_generator: str | None = None,
    raceline_iterations: int | None = None,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    sim: dict[str, object] | None = None,
    speed_margin: float = ...,
    initial_soc: float | None = None,
    tire_thermal: bool = True,
    initial_tire_temp_c: float | None = None,
    override: bool = False,
    us_schedule: dict[str, object] | None = None,
) -> TransientStint: ...
def vehicle_report(
    vehicle_dir: str,
    overrides: dict[str, bool | int | float | str] | None = None,
) -> dict[str, object]: ...
