# SPDX-License-Identifier: AGPL-3.0-only
"""Type stubs for the `outlap_core` extension module (shipped in the wheel by maturin)."""

import numpy as np
from numpy.typing import NDArray

DEFAULT_DS_M: float

class Tyre:
    notes: list[tuple[str, str]]
    citation: str
    fnomin: float
    unloaded_radius: float
    p_cold: float
    @staticmethod
    def load(path: str) -> Tyre: ...
    def forces(
        self,
        kappa: NDArray[np.float64],
        alpha: NDArray[np.float64],
        gamma: NDArray[np.float64],
        fz: NDArray[np.float64],
        p: NDArray[np.float64],
        vx: NDArray[np.float64],
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
        NDArray[np.float64],
    ]: ...
    def peak_mu(self, fz: float, p: float) -> tuple[float, float]: ...

class Track:
    @staticmethod
    def load(dir: str) -> Track: ...
    def name(self) -> str: ...
    def length(self) -> float: ...
    def is_closed(self) -> bool: ...
    def sample(self, ds_m: float) -> dict[str, NDArray[np.float64]]: ...

class Raceline:
    ds_m: float
    def s(self) -> NDArray[np.float64]: ...
    def n(self) -> NDArray[np.float64]: ...
    def line(self) -> Track: ...

class Envelope:
    notes: list[str]
    def ay_boundary(self, v: float, ax: float, g_normal: float) -> float: ...
    def accel_limit(self, v: float, g_normal: float) -> float: ...
    def brake_limit(self, v: float, g_normal: float) -> float: ...
    def drag_accel(self, v: float) -> float: ...
    def domain(self) -> list[list[float]]: ...
    def shape(self) -> list[int]: ...
    def mass_ref(self) -> float: ...

class Lap:
    lap_time_s: float
    tier: str
    fz_coupling: str
    flat_track: bool
    wheels: list[str]
    notes: list[str]
    resolved_hash: str
    envelope: Envelope | None
    def s(self) -> NDArray[np.float64]: ...
    def v(self) -> NDArray[np.float64]: ...
    def ax(self) -> NDArray[np.float64]: ...
    def ay(self) -> NDArray[np.float64]: ...
    def t(self) -> NDArray[np.float64]: ...
    def x(self) -> NDArray[np.float64]: ...
    def y(self) -> NDArray[np.float64]: ...
    def z(self) -> NDArray[np.float64]: ...
    # Per-wheel channels (shape n x 4, wheel order FL/FR/RL/RR); None for tier t0.
    def vertical_load_n(self) -> NDArray[np.float64] | None: ...
    def slip_ratio(self) -> NDArray[np.float64] | None: ...
    def slip_angle_rad(self) -> NDArray[np.float64] | None: ...
    def force_long_n(self) -> NDArray[np.float64] | None: ...
    def force_lat_n(self) -> NDArray[np.float64] | None: ...
    # Setup metrics (per station); None for tier t0.
    def understeer_gradient(self) -> NDArray[np.float64] | None: ...
    def aero_front_share(self) -> NDArray[np.float64] | None: ...
    # Slow-state channels (per station); None unless a coupled electrified stack was active.
    def state_of_charge(self) -> NDArray[np.float64] | None: ...
    def machine_temp_c(self) -> NDArray[np.float64] | None: ...

def min_curvature(
    track: Track,
    half_width_m: float,
    ds_m: float = 2.0,
    margin_m: float = 0.3,
    epsilon: float = 1e-8,
) -> Raceline: ...
def solve_lap(
    vehicle_dir: str,
    track: Track,
    ds_m: float = ...,
    raceline_ds_m: float | None = None,
    overrides: dict[str, bool | int | float | str] | None = None,
    conditions: dict[str, object] | None = None,
    tier: str | None = None,
    sim: dict[str, object] | None = None,
) -> Lap: ...
def vehicle_report(
    vehicle_dir: str,
    overrides: dict[str, bool | int | float | str] | None = None,
) -> dict[str, object]: ...
